language: objective-c
env:
  global:
    - secure: "Y/Og8Ij6b+TFcug1al84+uomUxT3Mi7Ssk97b3fw6Snmf7SNEhg8AcQv5joipa9qgHnEtFlQ53plxjX+5y244g2mwcXBBUVMrB7Nwnfu512fEqDnY1lck4lPRSDtNbtBOAiSOxjBGT7TspSyPRHu8HhzhRoCF4P1j+P4LKSAtq4="
    - secure: "k7un/9EQpGYSa+Xy+3I1fookpHTP7FP794/wOwQAojs1t7Vbce2+QyThEVHBYqLKeRle+Cp38BJ6h5GssYcNVyE5b+r8CKwDRfYfZzTmqLq0Hvhgm4rP24n03ZXOpwJQw344YFiZ7ilXYs73q1N4RFJLeHNStuDZwwYCEYRr+Gg="
    - secure: "nVXeMBnkQfCB2HNfwwbhgluSE5aHH7bZANMr+Vv7CEH9pEsMHDjr7Tu70BSQagQdP6/V2tyARAHDKVf9LOMfCCvREYWP4Cy2t02/QmlKC74rTgjpBd7KiDkqD1W8nWhOu9bqpvWCn66t9jqWJwWPaknhnAxy2ZeubZhaFDe7NQI="
install: true
before_script:
  - security create-keychain -p travis ios-build.keychain
  - security import ./travis/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import ./travis/dist.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import ./travis/dist.p12 -k ~/Library/Keychains/ios-build.keychain -P "$KEY_PASSWORD" -T /usr/bin/codesign
  - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  - cp ./travis/ProvisioningProfile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
script:
  - 'xctool -project HelloWorld.xcodeproj -scheme HelloWorld -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="iPhone Distribution" ONLY_ACIVE_ARCH=NO DSTROOT=build OBJROOT=build/objects SYMROOT=build build'
#   - 'xcrun -log -sdk iphoneos PackageApplication "build/Release-iphoneos/HelloWorld.app" -o "build/Release-iphoneos/HelloWorld.ipa" -sign "iPhone Distribution: Henrik Elstad Hodne (UFBY3M7V5Z)" -verbose -embed "travis/ProvisioningProfile.mobileprovision"'
  - 'xcodebuild -project HelloWorld.xcodeproj -scheme HelloWorld -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="iPhone Distribution" ONLY_ACTIVE_ARCH=NO DSTROOT=build OBJROOT=build/object SYMROOT=build archive'
  - 'ls -R build'
  - 'zip -r -9 "build/Release-iphoneos/HelloWorld.app.dSYM.zip" "build/Release-iphoneos/HelloWorld.app.dSYM"'
  - 'curl http://testflightapp.com/api/builds.json -F file="@build/Release-iphoneos/HelloWorld.ipa" -F dsym="@build/Release-iphoneos/HelloWorld.app.dSYM.zip" -F api_token="$TF_API_TOKEN" -F team_token="$TF_TEAM_TOKEN" -F distribution_lists="Internal" -F notes="Test Travis build" -v'
