language: objective-c
env:
  global:
    - secure: "BD9zaTvCAobiaMK0mwrRJoTExOXDHUbJms/bkJMn1MenvepmSoGkn1y5/bKCdLc+sC8sNg/+URmSqVIgjft31P5ORYiyIlG8qMDydMD2WJy4wlDRG3XGKJgum7P6hcxnyg/nE8N3U5kMFPAAAz670h6F0AP3BdMBItWKL2yanpc="
    - secure: "k7un/9EQpGYSa+Xy+3I1fookpHTP7FP794/wOwQAojs1t7Vbce2+QyThEVHBYqLKeRle+Cp38BJ6h5GssYcNVyE5b+r8CKwDRfYfZzTmqLq0Hvhgm4rP24n03ZXOpwJQw344YFiZ7ilXYs73q1N4RFJLeHNStuDZwwYCEYRr+Gg="
    - secure: "nVXeMBnkQfCB2HNfwwbhgluSE5aHH7bZANMr+Vv7CEH9pEsMHDjr7Tu70BSQagQdP6/V2tyARAHDKVf9LOMfCCvREYWP4Cy2t02/QmlKC74rTgjpBd7KiDkqD1W8nWhOu9bqpvWCn66t9jqWJwWPaknhnAxy2ZeubZhaFDe7NQI="
install: true
before_script:
  - security create-keychain -p travis ios-build.keychain
  - security import ./travis/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import ./travis/dist.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import ./travis/dist.p12 -k ~/Library/Keychains/ios-build.keychain -P "$KEY_PASSWORD" -T /usr/bin/codesign
script:
  - xctool -project HelloWorld.xcodeproj -scheme HelloWorld -sdk iphoneos -configuration Release ONLY_ACIVE_ARCH=NO DSTROOT=build OBJROOT=build/objects SYMROOT=build build
  - xcrun -log -sdk iphoneos PackageApplication "build/HelloWorld.app" -o "build/HelloWorld.ipa" -sign "iPhone Distribution: Henrik Elstad Hodne (UFBY3M7V5Z)" -embed "travis/ProvisioningProfile.mobileprovision"
  - zip -r -9 "build/HelloWorld.app.dSYM.zip" "build/HelloWorld.app.dSYM"
  - curl http://testflightapp.com/api/builds.json -F file="@build/HelloWorld.ipa" -F dsym="@build/HelloWorld.app.dSYM.zip" -F api_token="$TF_API_TOKEN" -F team_token="$TF_TEAM_TOKEN" -F distribution_lists="Internal" -F notes="Test Travis build" -v
